Belt_Reviewer_Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.LoginAndReg.urls', namespace = "login")),
     url(r'^BeltReviewer/', include('apps.Belt_Reviewer.urls', namespace = "beltReviewer"))
]

apps/Belt_Reviewer/urls.py
from django.conf.urls import url, include # Notice we added include
from . import views

urlpatterns = [
	url(r'^books$', views.index, name = "index"),
	url(r'^books/new$', views.createDisplay, name = "createDisplay"),
	url(r'^bookscreate$', views.create, name = "create"),
	url(r'^books(?P<id>\d+)$', views.show, name = "show"),
	url(r'^books(?P<id>\d+)/showuser$', views.showUser, name = "showUser"),
	url(r'^books(?P<id>\d+)/delete$', views.delete, name = "delete"),
	url(r'^bookslogout$', views.logout, name = "logout"),
	url(r'^booksNewReview$', views.newReview, name = "newReview")

]

apps/Belt_Reviewer/models.py
from __future__ import unicode_literals
from django.db import models
from ..LoginAndReg.models import User, LoginManager, RegisterManager
# Create your models here.


class Author(models.Model):
	name = models.CharField(max_length=100)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

class Book(models.Model):
	title = models.CharField(max_length=100)
	author_id = models.ForeignKey(Author)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

class Review(models.Model):
	review = models.TextField()
	rating = models.IntegerField()
	book_id = models.ForeignKey(Book)
	user_id = models.ForeignKey(User, related_name = 'userReviews')
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

apps/Belt_Reviewer/views.py
from django.shortcuts import render, HttpResponse, redirect
from models import Book, Review, Author
from ..LoginAndReg.models import User, LoginManager, RegisterManager
from django.core.urlresolvers import reverse
from django.db.models import Count 

def index(request):
	user = User.registerMgr.get(id = request.session['login'])
	context = {
        'book_reviews' : Review.objects.all(),
        'user_name': user.firstName,
        'books': Book.objects.all()
    }
	print context['books']
	return render(request, 'Belt_Reviewer/index.html', context)

def createDisplay(request):
	context = {
		'authors': Author.objects.all()
	}
	return render(request, 'Belt_Reviewer/addnew.html', context)

def create(request):
	author = Author(name = request.POST['author'])
	author.save()
	book = Book(title = request.POST['title'], author_id = author)
	book.save()
	user = User.registerMgr.get(id = request.session['login'])
	review = Review(review = request.POST['review'], rating = request.POST['rating'], book_id = book, user_id = user)
	review.save()
	return redirect(reverse('beltReviewer:index'))

def newReview(request):
	book = Book.objects.get(id = request.POST['title'])
	user = User.registerMgr.get(id = request.session['login'])
	review = Review(review = request.POST['review'], rating = request.POST['rating'], book_id = book, user_id_id = user.id)
	review.save()
	url = "/BeltReviewer/books" + str(book.id)
	return redirect(url)
	# return redirect(reverse('beltReviewer:index'))

def show(request, id):
	book = Book.objects.get(id = id)
	context = {
		'book_reviews': Review.objects.filter(book_id = book),
		'book': book
	}
	return render(request, 'Belt_Reviewer/show1.html', context)

def showUser(request, id):
	user = User.registerMgr.filter(id = id)
	context = {
		'users': user.annotate(reviewcount = Count('userReviews')),
		'books': Book.objects.filter(review__user_id = user)
	}
	return render(request, 'Belt_Reviewer/showuser.html', context)

def delete(request, id):
	review = Review.objects.filter(id = id)
	book = Book.objects.get(review = review)
	review.delete()
	url = "/BeltReviewer/books" + str(book.id)
	return redirect(url)
	# return redirect(reverse('beltReviewer:index'))

def logout(request):
    request.session['login'] = 0
    return redirect(reverse('login:index'))

apps/Belt_Reviewer/templates/Belt_Reviewer/addnew.html
<html>
<head>
	<title>Belt Review Create Page</title>
</head>
<body>
	<h1> Add A New Book Title and a Review </h1>
	<form action="{%url 'beltReviewer:create' %}" method='post'>
    {% csrf_token %}
          Book Title: <input type='text' name='title'> 
          <select name = "author">
          {% for author in authors %}
            <option value ="{{author.id}}">{{author.name}}</option>
          {% endfor %}
          </select>
          Author: <input type='text' name='author'>
          Review: <textarea rows="4" cols="50" name = 'review'></textarea>
          Rating:  
          <select name = "rating">
            <option value = 5> "5" </option>
            <option value = 4> "4" </option>
            <option value = 3> "3" </option>
            <option value = 2> "2" </option>
            <option value = 1> "1" </option>
          </select>
          <input type='submit' value='Add Book and Review'>
    </form>
    <a href="{%url 'beltReviewer:index' %}">Go Back to Display</a>
    <a href="{%url 'login:index' %}">Log Out</a>
</body>
</html>

apps/Belt_Reviewer/templates/Belt_Reviewer/index.html
<html>
<head>
	<title>Book Reviews</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
	<h1> Welcome, {{ user_name }} </h1>
 	<div class = "container">
 		<div class = "row">
 			<div class = "col-sm-6">
 				<h2>Recent Book Reviews</h2>
			  	{% for book_review in book_reviews %}
				   <a href="{%url 'beltReviewer:show' id=book_review.book_id.id %}">{{ book_review.book_id.title}}</a>
				   <p class = "message">Rating {{ book_review.rating}} </p>
				   <p class = "message"> <a href="{%url 'beltReviewer:showUser' id=book_review.user_id.id %}">{{ book_review.user_id.firstName}}</a>: {{book_review.review}} </p>
				   <p class = "message">{{ book_review.created_at}} </p>
			   	{% endfor %}
			</div>
 			<div class = "col-sm-6">
 				<h2>Other Books with Reviews</h2>
			  	{% for book in books %}
				   <a href="{%url 'beltReviewer:show' id=book.id %}">{{ book.title }}</a><br>
			   	{% endfor %}
			</div>
		</div>
	</div>
	<a href="{%url 'beltReviewer:createDisplay'%}">Add Book and Review</a>
	<a href="{%url 'beltReviewer:logout' %}">Log Out</a>
</body>
</html>

apps/Belt_Reviewer/templates/Belt_Reviewer/show1.html
<html>
<head>
	<title>Belt Reviewer Display One User</title>
</head>
<body>
	<div class = "container">
 		<div class = "row">
 			<div class = "col-sm-8 col-sm-offset-2">
 				<h1>{{ book.title }}</h1>
 				<h2>{{ book.author_id.name }}</h2>
 				<h2> Reviews</h2>
			  	{% for book_review in book_reviews %}
				   <p class = "message">Rating {{ book_review.rating}} </p>
				   <p class = "message">{{ book_review.user_id.firstName}}: {{ book_review.review }}</p>
				   <p class = "message">{{ book_review.created_at}} </p>
					{% if request.session.login == book_review.user_id.id %}
						<a href="{%url 'beltReviewer:delete' id=book_review.id %}">Delete</a>
					{% endif %}
			   	{% endfor %}
			</div>
		</div>
	</div>
	<form action="{%url 'beltReviewer:newReview' %}" method='post'>
    {% csrf_token %}
    	 <input type='hidden' name='title' value='{{book.id}}'> 
    	 <input type='hidden' name='author' value='{{book.author_id.id}}'>
          Review: <textarea rows="4" cols="50" name = 'review'></textarea>
          Rating:  
          <select name = "rating">
            <option value = 5> "5" </option>
            <option value = 3> "4" </option>
            <option value = 3> "3" </option>
            <option value = 2> "2" </option>
            <option value = 1> "1" </option>
          </select>
          <input type='submit' value='Submit Review'>
    </form>
	<a href="{%url 'beltReviewer:index' %}">Go Back to Display</a>
</body>
</html>

apps/Belt_Reviewer/templates/Belt_Reviewer/showuser.html
<html>
<head>
	<title>Show User Belt Reviewer</title>
</head>
<body>
	<div class = "container">
 		<div class = "row">
 			<div class = "col-sm-8 col-sm-offset-2">
 				<h2>User: NAME </h2>
			  	{% for user in users %}
				   <p class = "message">Name: {{ user.firstName }} {{user.lastName }} </p>
				   <p class = "message">Email: {{ user.email }} </p>
				   <p class = "message">Total Reviews: {{ user.reviewcount }} </p>
			   	{% endfor %}
			</div>
		</div>
	</div>
	<h1>Posted Reviews on the following books:</h1>
		{% for book in books %}
			<p> {{ book.title }}</p>
		{% endfor %}
	<a href="{%url 'beltReviewer:index' %}">Home</a>
	<a href="{%url 'beltReviewer:createDisplay' %}">Add Book and Review</a>
	<a href="{%url 'beltReviewer:logout' %}">Logout</a>
</body>
</html>